# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA : switched to validate to prevent filghting flyway o it's own and change schema which breaks migrations and auditability now it's controlled by flyway migration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

# Server
server.port=8081

# Max request size for base64 videos (JSON bodies)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1


# Logging
logging.level.org.hibernate.SQL=DEBUG
# less noisy than trace for normal development
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG

# JWT
jwt.secret=${JWT_SECRET}
# 24 hours in milliseconds 900000 for normal setup
jwt.expiration=900000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Where backend redirects after OAuth success (your Next.js route)
app.oauth2.frontend-redirect=http://localhost:3000/auth/oauth-callback

# Email verification
app.email-verification.ttl-minutes=30
# Dev mode: return token/code in API response so you can test without sending emails.
# Set false later when you integrate real email sending.
app.email-verification.dev-return=false
app.password-reset.dev-return=false

# Brevo SMTP (Transactional)
spring.mail.host=${BREVO_HOST}
spring.mail.port=587
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Your app settings
app.mail.from=${BREVO_MAIL}
app.frontend.base-url=http://localhost:3000